# Generated by Django 2.0.1 on 2018-01-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20180113_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(related_name='artists', to='musicapp.Album'),
        ),
    ]
