# Generated by Django 2.0.1 on 2018-01-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_auto_20180113_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='albums', to='musicapp.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='albums', to='musicapp.Track'),
        ),
    ]
