# Generated by Django 2.0.1 on 2018-01-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20180113_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.DurationField(verbose_name='Длительность'),
        ),
    ]
