# Generated by Django 2.0.1 on 2018-01-13 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_auto_20180113_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('-time_added',), 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AddField(
            model_name='track',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Имя тэга'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_name',
            field=models.CharField(max_length=30, verbose_name='Трек'),
        ),
    ]
