# Generated by Django 2.0.1 on 2018-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_auto_20180113_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='tracks',
        ),
        migrations.RemoveField(
            model_name='track',
            name='time_added',
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='tracks', to='musicapp.Album'),
        ),
        migrations.AddField(
            model_name='track',
            name='order_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер в альбоме'),
        ),
    ]
