# Generated by Django 2.0.1 on 2018-01-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_auto_20180113_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-album_name',), 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-genre_name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('-track_name',), 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=15, null=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='Album', to='musicapp.Genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(verbose_name='Выпущен'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='Artist', to='musicapp.Album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='Track', to='musicapp.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='order_no',
            field=models.IntegerField(verbose_name='Номер в альбоме'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_name',
            field=models.CharField(max_length=40, verbose_name='Трек'),
        ),
    ]
