# Generated by Django 2.0.1 on 2018-01-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_auto_20180114_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-genre_name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre_name',
        ),
    ]
