# Generated by Django 2.0.1 on 2018-01-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_auto_20180114_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='Album', to='musicapp.Genre'),
        ),
    ]
