# Generated by Django 2.0.1 on 2018-01-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0013_auto_20180114_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('album_name',), 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('artist_name',), 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('track_name',), 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='Album', to='musicapp.Genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, related_name='Artist', to='musicapp.Album'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Жанр'),
        ),
    ]
