# Generated by Django 2.0.1 on 2018-01-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0014_auto_20180114_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('album', 'order_no'), 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='Artist', to='musicapp.Album'),
        ),
    ]
