# Generated by Django 2.0.1 on 2018-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0015_auto_20180114_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='Album', to='musicapp.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='Artist', to='musicapp.Album', verbose_name='Альбомы'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='Track', to='musicapp.Album', verbose_name='Альбом'),
        ),
    ]
