# Generated by Django 2.0.1 on 2018-01-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0016_auto_20180118_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='albums', to='musicapp.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='artists', to='musicapp.Album', verbose_name='Альбомы'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='tracks', to='musicapp.Album', verbose_name='Альбом'),
        ),
    ]
