# Generated by Django 2.0.1 on 2018-01-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0017_auto_20180126_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
