# Generated by Django 2.0.1 on 2018-01-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0018_album_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, upload_to='images/covers/'),
        ),
    ]
