# Generated by Django 2.0.1 on 2018-01-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0019_auto_20180128_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/tracks/'),
        ),
    ]
